version: '3'

services:
  app: 
    build: .
    platform: linux/amd64
    ports:
      - "3000:3000" 
      - "9229:9229"
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "." 
    expose:
      - 3000
      - 9229
    volumes:
      - .:/home/node/app
    depends_on:
      - db2
  db2:
    build: .docker/postgres
    platform: linux/amd64
    container_name: bankaccount-db2
    restart: always
    tty: true
    ports:
    - '5432:5432'
    expose:
      - 5432
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bankaccount

  pgadmin:
    platform: linux/amd64

    image: dpage/pgadmin4
    container_name: bankaccount-pgadmin2
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db2