version: '3'

services:
  app:
    build: .
    platform: linux/amd64
    entrypoint: .docker/entrypoint.sh
    container_name: bankaccount-app
    ports:
      - '3333:3333'
    expose:
      - 3333
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    platform: linux/amd64
    container_name: bankaccount-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    expose:
    - 5432
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bankaccount

  pgadmin:
    platform: linux/amd64
    image: dpage/pgadmin4
    container_name: bankaccount-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db